### ISSUE TITLE
需要确定Student实体类的属性

### ISSUE THREAD

**Issue by guancg** [usedtolove/tz-tpcs#10]

**Comment by usedtolove** [comment]
Dear 管成功,

    Student实体类的属性，
    已经初步调整好，并合并到 master 
    
    有不明白的，随时问。
    



胡荆陵 
教育事业部
Mobile: 15370077255
Email: hujl@sz-tz.org
Address: 苏州市烽火路80号
 
发件人： guancg
发送时间： 2015-01-23 10:51
收件人： usedtolove/tz-tpcs
抄送： Julian Hu
主题： [tz-tpcs] 需要确定Student实体类的属性 (#10)
