### ISSUE TITLE
关于知识库(Knowledge)实体类的设计

### ISSUE THREAD

**Issue by usedtolove** [usedtolove/tz-tpcs#4]
目前 Knowledge 如何设定？

之前的设定：
Knowledge 关联 Course (课程)，
Course 关联 Stage (阶段)，

现在的设定：
但由于知识点可以是一颗无限层的树状结构，
一个父知识点，可能依赖多个子知识点。
是否可以做自关联 (类似部门树)？
将课程，阶段等都看成比较上层的知识点，
后期如果有关课程，阶段等查询，只要在 Knowledge 中增加属性即可。

**Comment by yejf** [comment]
同意，知识点设计成自关联的模式，将来以“树”的方式呈现，并且可以动态添加节点，每个节点包含但不限于如下数据：
知识点代号
知识点名称
知识点内容[可做成富文本框]
