### ISSUE TITLE
BUG1:员工管理

### ISSUE THREAD

**Issue by yejf** [usedtolove/tz-tpcs#40]
问题点1：
新增员工成功后当前部门的员工列表数据不正确
问题点2：
删除一个没有员工的部门后，建议回到它的上级部门，并显示上级部门的员工列表，目前好象是不在任何地方。
问题点3：
每页显示的条目数建议改为 10条。
问题点4：
新增员工成功后，左边的树节点应该是回到所加员工所在的部门节点上

**Comment by usedtolove** [comment]
以上问题已修复
