### ISSUE TITLE
Task:开发实训过程管理的原型界面

### ISSUE THREAD

**Issue by yejf** [usedtolove/tz-tpcs#42]
实现过程管理原型界面，包含：
1.请假
2.违纪
3.转班
4.退学
5.学员访谈
6.学员补课
7.模拟面试
等页面

**Comment by yejf** [comment]
除了7.模拟面试　原型外，再加学员评价页面　已全部完成

**Comment by usedtolove** [comment]
代码实现新开 issue #43
