### ISSUE TITLE
删除学员时的异常处理

### ISSUE THREAD

**Issue by yejf** [usedtolove/tz-tpcs#49]
删除学员时涉及到数据完整性的检测,目前是后台出现异常,而前台没有任何提示,建议修复, 策略如下:
后台抛出数据完整型约束异常时,可以通过前台提示友好信息,告知用户此学员有其它相关的数据有效,暂不能删除.

**Comment by yejf** [comment]
追加一个, 删除班级时同样针对异常的处理有问题,删除一个已经存在学员的班级时,直接在前台页面看到后以台的异常堆栈信息, 如下:
"HTTP Status 500 - Request processing failed; nested exception is org.springframework.dao.DataIntegrityViolationException: could not execute statement"

**Comment by usedtolove** [comment]
目前已对Clazz和Student实体类的删除操作，
进行 DataIntegrityViolationException 异常捕获，
并提示在页面上。
Clazz由于开发较早，效果欠佳，仅用alert提示框；
Student由于已使用AngularJS重构，效果还行。

后面的项目，由于实体类之间的关联较多，
因此，可以需要在开发期间，针对有可能存在数据关联的对象，
在进行删除操作时，都对 DataIntegrityViolationException 异常进行捕获处理。

bug已修复。

**Comment by yejf** [comment]
Testing PASS,
确实 toastr显示的效果好很多, 比传统的alert漂亮多了!
