### ISSUE TITLE
普通用户登录后,没有权限访问首页

### ISSUE THREAD

**Issue by yejf** [usedtolove/tz-tpcs#50]
以yejf@sz-tz.org用户登录后,出现"AccessDeniedPage" 的页面提示,但是点击"返回"button时,无法返回,只能通过URL来访问, 此问题在完成权限分配时考虑进去,也许在权限分配完成后,就会自动修复,请注意一下.

**Comment by usedtolove** [comment]
通过2方面来解决：
1）所有系统内置角色，在数据初始化时，补充分配首页的逻辑；
2）后续通过人为新增的自定义角色，在新增保存操作时，补充分配默认菜单资源逻辑。

**Comment by yejf** [comment]
测试通过,
我接下来要设计用户角色设置的页面了,具体周一再与你讨论是分开做,还是放在一个页面中.

**Comment by usedtolove** [comment]
关于分配角色给用户的功能，
已转新 issue #53 完成，
此issue 关闭.
