### ISSUE TITLE
实现【实训过程】模块的【违纪】功能

### ISSUE THREAD

**Issue by usedtolove** [usedtolove/tz-tpcs#51]

**Comment by usedtolove** [comment]
此 issue 是由 #43 分出来的，
主要是便于后面各功能点的独立追踪。
在 #43 中所有指定功能都实现后，
#43 才会 close。

**Comment by yejf** [comment]
基本功能测试通过, 后期考虑加入自动扣除学员的分值[initialScore],此功能后面再加入
