### ISSUE TITLE
员工管理中,员工不能修改部门

### ISSUE THREAD

**Issue by yejf** [usedtolove/tz-tpcs#54]
员工管理中的,编辑某个员工时,修改不了他的部门

**Comment by usedtolove** [comment]
在开发环境下，
按以下操作顺序，无法重现问题：
1.登录系统；
2.员工>员工列表;
3.双击员工信息，进入编辑页面；
4.选择一个不同的部门，点击确定
5.回到员工列表页面，已在新部门。
请再次确认bug现象或原因。

**Comment by yejf** [comment]
测试OK
