### ISSUE TITLE
角色资源设置时的BUG

### ISSUE THREAD

**Issue by yejf** [usedtolove/tz-tpcs#55]
角色资源设置时, 如果给某个角色的资源设置时,只选中某个模块下的部份功能,而不是所有功能时,则被分配这个角色的用户登录后,是看不到这个模块的[一级菜单中不显示]

**Comment by usedtolove** [comment]
上述的 bug 已于 commit https://github.com/usedtolove/tz-tpcs/commit/c770250ea28efe956d6bde9746cd9da015196cbb 修复，
待测试。

**Comment by yejf** [comment]
测试OK!
