### ISSUE TITLE
导入学员时,生日属性值通过身份证的值自动生成,无需手动填写

### ISSUE THREAD

**Issue by yejf** [usedtolove/tz-tpcs#56]
目前导入学员信息功能中,excel表中即有身份证列,也有生日列,所以,可以实现生日列的值由身份证来的值为计算出来,这样,导入的模板中就不用写生日这一列了.

**Comment by yejf** [comment]
finished it

**Comment by yejf** [comment]
need test

**Comment by yejf** [comment]
测试时,发现如下问题:
1.导入是成功的,后台打印的信息生日的数据是正确的.
2.但是,在学员列表中显示的生日是一个毫秒数,不是日期格式, 可以看图
3. 进入编辑页面,生日又显示是正确的,如图:
![2](https://cloud.githubusercontent.com/assets/4973886/8080457/506c3c58-0f9f-11e5-93e7-5d6c3b090b51.png)
![3](https://cloud.githubusercontent.com/assets/4973886/8080462/52b65bd8-0f9f-11e5-91db-35086ad0f401.png)

初步判断下来后台的数据是正确的,是否有可能是JSP或是页面模板显示时的问题!
请确认一下

**Comment by usedtolove** [comment]
上述的 bug 已于 commit https://github.com/usedtolove/tz-tpcs/commit/c770250ea28efe956d6bde9746cd9da015196cbb 修复，
待测试。

**Comment by yejf** [comment]
测试通过
